### ISSUE TITLE
create images folder and move images inside

### ISSUE THREAD

**Issue by scriptnull** [scriptnull/yali#1]
README.md contains one image at this point, which is uploaded to GitHub assets.

We will try to self contain the resources as much as possible. 

So, it would be good to download the image and commit it under `images` folder and update the respective references in the README.md file.

**Comment by djovercash** [comment]
May I do this ticket?

**Comment by Raahul-Singh** [comment]
I would like to do this.

**Comment by scriptnull** [comment]
Hey all! Thank you for your interest. But we just have few PRs already in place for this.

https://github.com/scriptnull/yali/pull/2
https://github.com/scriptnull/yali/pull/3
https://github.com/scriptnull/yali/pull/4

**Comment by scriptnull** [comment]
This is now fixed by https://github.com/scriptnull/yali/pull/3. So closing this.
