### ISSUE TITLE
Add Artwork Section in README.md

### ISSUE THREAD

**Issue by scriptnull** [scriptnull/yali#5]
This issue is for people who are just looking out to raise their first PR! (on github or on this project)

If you are new to git + github and interested to learn how to contribute, this is perfect for you! To learn how to make changes and submit your changes for review, please refer to [this guide](https://github.com/firstcontributions/first-contributions).

Have fun! :cake: 

---

This issues is about adding details about the logo of the project.

Task is to edit README.md file in the root of project to include the below content in-between the `Contributing` and `License` sections.

```
## Artwork
Yali is a [mythical creature portrayed as part lion, part elephant and part horse](https://en.wikipedia.org/wiki/Yali_(mythology)) - this acted as the inspiration for the artwork.

Yali's artwork was designed and created by [Vasanth Selvam](https://dribbble.com/11CS103) and is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. Check `images` directory for more variations of the artwork.
```

**Comment by HCSolomon** [comment]
Hello, I would like to take on this project
